name: Docker image build

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: raccoondev/push-docker-gcr
      with:
        gcr_host: eu.gcr.io
        image_name: my_image
        image_tag: latest
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}